spring:
  datasource:
    url: jdbc:mysql://localhost:3307/empresa
    username: root
    password: 88510-12PyJsxPMV**
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql : true
    hibernate:
      ddl-auto : update
